# Generated by Django 4.0.4 on 2022-05-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_alter_customerdata_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
